[package]
name = "atom-desktop"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "atom-desktop"
path = "src/main.rs"

[dependencies]
atom-core  = { path = "../atom-core" }
wgpu       = "29"
winit      = "0.30"
egui       = "0.34"
egui-wgpu  = "0.34"
egui-winit = "0.34"
pollster   = "0.4"
bytemuck   = { version = "1", features = ["derive"] }
glam       = "0.33"
image      = { version = "0.25", default-features = false, features = ["png"] }
